backend:
  name: git-gateway
  branch: main # Siten 'main' dalında değilse 'master' yapabilirsin

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "bulmaca"
    label: "Bulmaca Kelimeleri"
    folder: "data" # Kelimelerin yükleneceği klasör
    extension: "json"
    format: "json"
    create: true
    slug: "{{cevap}}"
    fields:
      - {label: "Soru (Tanım)", name: "soru", widget: "string"}
      - {label: "Cevap", name: "cevap", widget: "string"}
      - {label: "Harf Sayısı", name: "harf", widget: "number"}
      - {label: "Kategori", name: "kategori", widget: "string", required: false}
